name: Build, Scan, and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false  # Ne pas pousser encore l'image

      - name: Scan Docker image for vulnerabilities
        uses: aquasecurity/trivy-action@v0.8.0
        with:
            image: ghcr.io/${{ github.actor }}/ue19-lab-05:latest
            format: table
            exit-code: 1

      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.actor }}/ue19-lab-05:latest
